./" Manpage for script
.TH man 1 „10.05.2023" ""Version 2.0.1 Alfa Beta Delta Gamma BP Auchan" "encodeAndDecode man page"

.SH NAME
encodeAndDecode - The aim of the project is to create a program that can hide a text message in an image using LSD (Least Significant Digit)

.SH SYNOPSIS
encodeAndDecode [\fI-h\fR] [\fI-v\fR]

.SH DESCRIPTION
The aim of the project is to create a program that can hide a text message in an image using LSD (Least Significant Digit).
Depending on the Least Significant Digit value, the last pixel value will be added or subtracted.
The program has the ability to encrypt and decrypt messages.

.SH OPTIONS
None

.SH BUGS
No known bugs.

.SH AUTHOR
written by Piotr Kijoch (https://github.com/PanBudzik)
